extends SceneTree
const Env = preload("res://scripts/core/settlement_environment.gd")
const Sampler = preload("res://scripts/core/settlement_sampler.gd")
const SOURCE := "res://assets/terrain/eurasia_uniform_river_map_source.json"
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var source := (load(MapSource.texture_path(SOURCE)) as Texture2D).get_image()
	var analysis := source.duplicate()
	analysis.resize(256,256,Image.INTERPOLATE_NEAREST)
	var land: PackedByteArray = TerrainMapGenerator._all_land_geometry(analysis).mask
	var latitudes := PackedFloat32Array()
	for y in range(256): latitudes.append(MapSource.latitude_at_y((y+.5)/256.0,18,57,SOURCE))
	var aspect := MapSource.aspect_ratio(SOURCE)
	var old := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true)
	var before := Sampler.sample(source,land,old,500,aspect,12345)
	var next := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true,"uniform_v1")
	assert(old.environment_id!=next.environment_id and not next.cache_hit)
	assert(old.hydrology.features==next.hydrology.features and old.hydrology.flow==next.hydrology.flow)
	var valley := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true,"valley_v1")
	assert(valley.environment_id!=next.environment_id and not valley.cache_hit)
	assert(valley.hydrology.features==old.hydrology.features and valley.hydrology.flow==old.hydrology.flow)
	var raw: PackedFloat32Array = valley.suitability.duplicate()
	var reserved := TerrainMapGenerator._reserve_hydrology_docks(valley,analysis,aspect,500)
	var unfloored := Sampler.sample(source,land,valley,500,aspect,12345,reserved)
	var floored := Sampler.sample(source,land,valley,500,aspect,12345,reserved,{"minimum":0.05,"maximum":1.0})
	assert(unfloored.ok and floored.ok and unfloored.positions!=floored.positions)
	assert(valley.suitability==raw)
	var valley_cached := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true,"valley_v1")
	assert(valley_cached.cache_hit and valley_cached.suitability==raw)
	var cached := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true)
	assert(cached.cache_hit and old.environment_id==cached.environment_id)
	assert(cached.water==old.water and cached.suitability==old.suitability)
	var after := Sampler.sample(source,land,cached,500,aspect,12345)
	assert(before.ok and after.ok and before.positions==after.positions)
	latitudes[100] += 0.1
	var changed := Env.build(source,analysis,land,latitudes,aspect,"web_mercator",true,MapSource.hydrology_network(SOURCE),true,"uniform_v1")
	assert(not changed.cache_hit and changed.environment_id!=next.environment_id)
	print("UNIFORM_CACHE_OK old_new_valley_old_layout_preserved=1 latitude_invalidates=1 river_flow_unchanged=1 density_does_not_mutate_environment=1")
	quit()
